name: Deploy CRM Feature 2

on:
  workflow_dispatch:   # manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for OIDC
      contents: read 

    env:
      TF_VAR_environment: dev   # Terraform will pick this up automatically
      TF_VAR_cognito_user_pool_id: ${{ secrets.COGNITO_USER_POOL_ID }}
      AWS_REGION: ap-southeast-1   # or use a GitHub secret if you want per-env flexibility

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Package Clients & Accounts Lambdas
        run: |
          # Install wheels built for the Lambda runtime (Linux x86_64, Python 3.11)
          PIP_LAMBDA="--platform manylinux2014_x86_64 --implementation cp --python-version 3.11 --only-binary=:all:"

          # -------- Clients --------
          mkdir -p build/clients
          cp lambdas/clients/clients.py build/clients/
          pip install -r lambdas/clients/requirements.txt -t build/clients/ $PIP_LAMBDA
          cd build/clients
          zip -r ../../lambdas/clients.zip ./*
          cd ../..

          # -------- Accounts --------
          mkdir -p build/accounts
          cp lambdas/accounts/accounts.py build/accounts/
          pip install -r lambdas/accounts/requirements.txt -t build/accounts/ $PIP_LAMBDA
          cd build/accounts
          zip -r ../../lambdas/accounts.zip ./*  
          cd ../..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra
        run: TF_LOG=ERROR terraform apply -auto-approve tfplan #TF_LOG=DEBUG terraform apply -auto-approve tfplan

      - name: Terraform Destroy (on failure)
        if: failure() || cancelled()
        working-directory: infra
        run: terraform destroy -auto-approve
      # ==============================
      # Capture Terraform outputs
      # ==============================

      - name: Export API URL to JSON
        working-directory: infra
        run: terraform output -json > tf_outputs.json

      - name: Show API URL
        run: cat infra/tf_outputs.json | jq -r .api_invoke_url.value
